In [7]:
file_path = "../data/processed/processed_data.csv"

import pandas as pd

df = pd.read_csv(file_path)

df.head()

,TransactionId,ProviderId,ProductId,ProductCategory,ChannelId,Amount,Value,TransactionStartTime,PricingStrategy,FraudResult,...,TransactionStartTime_hour_cos,TransactionStartTime_day_sin,TransactionStartTime_day_cos,Amount_sum,Amount_mean,Amount_count,Amount_std,Amount_median,Amount_min,Amount_max
0,TransactionId_76871,ProviderId_6,ProductId_10,airtime,ChannelId_3,1000.0,1000,2018-11-15 02:18:49+00:00,2,0,...,0.866025,0.101168,-0.994869,109921.75,923.712185,119,3042.294251,500.0,-5000.0,20000.0
1,TransactionId_73770,ProviderId_4,ProductId_6,financial_services,ChannelId_2,-20.0,20,2018-11-15 02:19:08+00:00,2,0,...,0.866025,0.101168,-0.994869,109921.75,923.712185,119,3042.294251,500.0,-5000.0,20000.0
2,TransactionId_26203,ProviderId_6,Other,airtime,ChannelId_3,500.0,500,2018-11-15 02:44:21+00:00,2,0,...,0.866025,0.101168,-0.994869,1000.00,500.000000,2,0.000000,500.0,500.0,500.0
3,TransactionId_380,ProviderId_1,Other,Other,ChannelId_3,20000.0,21800,2018-11-15 03:32:55+00:00,2,0,...,0.707107,0.101168,-0.994869,228727.20,6019.136842,38,17169.241610,1000.0,-10000.0,100000.0
4,TransactionId_28195,ProviderId_4,ProductId_6,financial_services,ChannelId_2,-644.0,644,2018-11-15 03:34:21+00:00,2,0,...,0.707107,0.101168,-0.994869,228727.20,6019.136842,38,17169.241610,1000.0,-10000.0,100000.0

In [3]:
cat_features = [col for col in df.columns if df[col].dtype == "object"]

# frequency

for col in cat_features:
    freq = df[col].value_counts()
    print(f"Column: {col}")
    print(freq)
    print()

Column: TransactionId
TransactionId
TransactionId_76871     1
TransactionId_73770     1
TransactionId_26203     1
TransactionId_380       1
TransactionId_28195     1
                       ..
TransactionId_89881     1
TransactionId_91597     1
TransactionId_82501     1
TransactionId_136354    1
TransactionId_35670     1
Name: count, Length: 95662, dtype: int64

Column: ProviderId
ProviderId
ProviderId_4    38189
ProviderId_6    34186
ProviderId_5    14542
ProviderId_1     5643
Other            3102
Name: count, dtype: int64

Column: ProductId
ProductId
ProductId_6     32635
ProductId_3     24344
ProductId_10    15384
ProductId_15    11964
Other           11335
Name: count, dtype: int64

Column: ProductCategory
ProductCategory
financial_services    45405
airtime               45027
Other                  5230
Name: count, dtype: int64

Column: ChannelId
ChannelId
ChannelId_3    56935
ChannelId_2    37141
Other           1586
Name: count, dtype: int64

In [4]:
cat_features

['TransactionId', 'ProviderId', 'ProductId', 'ProductCategory', 'ChannelId']

In [ ]:
numeric_features = [col for col in df.columns if df[col].dtype != "object"]

numeric_features = [
    'Amount', 'Value', 'PricingStrategy', 'FraudResult', 'TransactionStartTime_year', 'TransactionStartTime_month',
    'TransactionStartTime_day', 'TransactionStartTime_hour', 'TransactionStartTime_minute', 'TransactionStartTime_dayofweek',
    'TransactionStartTime_is_weekend', 'TransactionStartTime_days_since', 'TransactionStartTime_weeks_since', 'TransactionStartTime_hour_sin',
    'TransactionStartTime_hour_cos', 'TransactionStartTime_day_sin', 'TransactionStartTime_day_cos', 'Amount_sum', 'Amount_mean',
    'Amount_count', 'Amount_std', 'Amount_median', 'Amount_min', 'Amount_max'
]

['Amount',
 'Value',
 'PricingStrategy',
 'FraudResult',
 'TransactionStartTime_year',
 'TransactionStartTime_month',
 'TransactionStartTime_day',
 'TransactionStartTime_hour',
 'TransactionStartTime_minute',
 'TransactionStartTime_dayofweek',
 'TransactionStartTime_is_weekend',
 'TransactionStartTime_days_since',
 'TransactionStartTime_weeks_since',
 'TransactionStartTime_hour_sin',
 'TransactionStartTime_hour_cos',
 'TransactionStartTime_day_sin',
 'TransactionStartTime_day_cos',
 'Amount_sum',
 'Amount_mean',
 'Amount_count',
 'Amount_std',
 'Amount_median',
 'Amount_min',
 'Amount_max']

In [6]:
ENCODE_FILE_PATH = "../data/processed/processed_data_encoded.csv"

df = pd.read_csv(ENCODE_FILE_PATH)

df.dtypes

ProviderId_Other                      float64
ProviderId_ProviderId_1               float64
ProviderId_ProviderId_4               float64
ProviderId_ProviderId_5               float64
ProviderId_ProviderId_6               float64
ProductId_Other                       float64
ProductId_ProductId_10                float64
ProductId_ProductId_15                float64
ProductId_ProductId_3                 float64
ProductId_ProductId_6                 float64
ProductCategory_Other                 float64
ProductCategory_airtime               float64
ProductCategory_financial_services    float64
ChannelId_ChannelId_2                 float64
ChannelId_ChannelId_3                 float64
ChannelId_Other                       float64
Amount                                float64
Value                                 float64
PricingStrategy                       float64
FraudResult                           float64
TransactionStartTime_year             float64
TransactionStartTime_month            float64
TransactionStartTime_day              float64
TransactionStartTime_hour             float64
TransactionStartTime_minute           float64
TransactionStartTime_dayofweek        float64
TransactionStartTime_is_weekend       float64
TransactionStartTime_days_since       float64
TransactionStartTime_weeks_since      float64
TransactionStartTime_hour_sin         float64
TransactionStartTime_hour_cos         float64
TransactionStartTime_day_sin          float64
TransactionStartTime_day_cos          float64
Amount_sum                            float64
Amount_mean                           float64
Amount_count                          float64
Amount_std                            float64
Amount_median                         float64
Amount_min                            float64
Amount_max                            float64
dtype: object